### ISSUE TITLE
Auto-Implemented properties written several lines when using attributeGroup

### ISSUE THREAD

**Issue by verdie-g** [mganss/XmlSchemaClassGenerator#125]
```xml
<xs:attributeGroup name="Common">
  <xs:attribute name="name" type="xs:string"></xs:attribute>
</xs:attributeGroup>

<xs:complexType name="A">
  <xs:attributeGroup ref="Common"/>
</xs:complexType>
```
generates
```csharp
public partial interface ICommon
{
  string Name
  {
    get;
    set;
  }
}
```
The property is on several line. Is it possible to one-line this ?

**Comment by mganss** [comment]
This comes from CodeDom: https://github.com/mganss/XmlSchemaClassGenerator/blob/827a00cc383362d2a91111a11f70d529307e0256/XmlSchemaClassGenerator/TypeModel.cs#L721-L727

This is actually less hacky than the other places where auto properties are generated, e.g. 
https://github.com/mganss/XmlSchemaClassGenerator/blob/827a00cc383362d2a91111a11f70d529307e0256/XmlSchemaClassGenerator/TypeModel.cs#L794

I think I did the latter because I simply wasn't aware of the non-hacky way to do this and the interface implementation was added later.

**Comment by verdie-g** [comment]
But the hacky way generates a one line property unlike HasGet/HasSet. I have tried using the same hack in AddInterfaceMembersTo but I ended up with:
```csharp
public partial interface ICommon
{
  string Name { get; set; }
  {
  }
}
```
Would you know how to fix that ?

**Comment by mganss** [comment]
Did you change the `CodeMemberProperty` to a `CodeMemberField`?

**Comment by verdie-g** [comment]
I think I've tried very quickly both without much thinking. If you have an idea how to do that I'll take it, otherwise I'll think a little and will read the doc for CodeMember*.
