### ISSUE TITLE
No error message when file doesn't exist

### ISSUE THREAD

**Issue by verdie-g** [mganss/XmlSchemaClassGenerator#130]
Passing a non-existing file to the cli arguments should exit 1 and print a message on stderr.

I can do the PR but I don't understand why each is [checked to be a well formed uri](https://github.com/mganss/XmlSchemaClassGenerator/blob/master/XmlSchemaClassGenerator.Console/Program.cs#L101)

**Comment by mganss** [comment]
That's because you can also pass URLs 😄 

Checking for the existence of files passed on the command line is not straight-forward because you can pass globs (e.g. "/home/*/**/*.xsd" does not exist as-is but might expand to existing paths). Perhaps only check those that don't have any glob characters in them? Or fail if a glob does not expand to any files (like `ls` does)?
