### ISSUE TITLE
Avoid generating invalid code

### ISSUE THREAD

**Issue by leus** [mganss/XmlSchemaClassGenerator#172]
When using as-is with [this schema for DTSX packages](https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx/61d22b48-f3d3-4ef9-b5c3-c70598a4d688), I get the following error:

`Error	CS0542	'ConfigurationType': member names cannot be the same as their enclosing type	`
Is there an easy way to avoid creating properties with the same name as their class?

**Comment by mganss** [comment]
Generally, name clashes can occur and there is currently no built-in way to avoid them (except for a few heuristics). But in this particular case, I can't repro. I'll admit I just tried the [DTS XSD (5.1)](https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx/d578be53-65c5-424e-8757-1e8c4e33b56b) but the other xsds don't contain `ConfigurationType`. Which XML Schema type  exactly  causes the issue?

**Comment by leus** [comment]
I had used the 2014-01 version. I changed back to the same 5.1 version and it works. I'd like to go back to the other version because it contains this extra property that may be needed in the future (I'm working on an internal SSIS package analysis utility).

I'll try to come up with a minimal example and create a unit test to see if I can help with this issue.

**Comment by leus** [comment]
I still have some issues with [this attached schema (Package.zip)](https://github.com/mganss/XmlSchemaClassGenerator/files/4324490/Package.zip), which I have edited to remove most of its contents. Here's the definition for `ConnectionManagerObjectType`:
```xsd
   <xs:complexType name="ConnectionManagerType">
     <xs:sequence>
       <xs:element name="PropertyExpression"
                   type="DTS:PropertyExpressionElementType"
                   minOccurs="0" maxOccurs="unbounded"/>
       <xs:element name="ObjectData"
                   type="DTS:ConnectionManagerObjectDataType"/>
     </xs:sequence>
     <xs:attributeGroup ref="DTS:BasePropertyAttributeGroup"/>
     <xs:attributeGroup ref="DTS:ConnectionManagerAttributeGroup"/>
     <xs:attribute name="refId" type="xs:string" use="required" 
                   form="qualified"/>
   </xs:complexType>
```
I don't see the `BasePropertyAttributeGroup` members generated, nor the `refId` attribute. Also, the `ConnectionString` attribute doesn't get set when deserializing. The declaration for this class is as follows:
```csharp
public partial class ConnectionManagerObjectDataConnectionManagerType : IConnectionManagerConnectionManagerAttributeGroup
    { ... }
```
I'll get the source code and try to dig in, but any pointers are welcome.

**Comment by mganss** [comment]
There was a problem with the way `form="qualified"` was handled. I hope to have fixed this now (see [Form Attribute Binding Support](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/1ksfew25%28v%3dvs.100%29) on how xsd.exe handles this).

Now your .dtsx example file deserializes, except for the `CreationDate` attribute which is not schema valid. Currently I think the only way to work around this is to patch the schema to use `xs:string` for the attribute.

Regarding the original issue of `ConfigurationType` we've actually had [this case covered](https://github.com/mganss/XmlSchemaClassGenerator/blob/c8971df7142912189223358db56b274af6d36830/XmlSchemaClassGenerator/ModelBuilder.cs#L475-L478) (more or less) but only if you don't generate interfaces (use `-t-`) because when we're generating an interface we don't know which class will eventually implement it.

**Comment by leus** [comment]
Yes, indeed I had to use string for the `CreationDate` attribute. It is good to know about not generating interfaces.

Thank you for your work!
