### ISSUE TITLE
Required Attribute for MinOccurs 

### ISSUE THREAD

**Issue by pavan1386** [mganss/XmlSchemaClassGenerator#200]
Hi,
I've started using this tool instead of xsd.exe and so far it has been a godsend. However, I notice that the "minOccurs", "maxOccurs" restrictions are not reflected on the generated classes (no [required] attribute or similar). Is this part of the functionallity?

Thank you.

**Comment by mganss** [comment]
This functionality is not present currently.

**Comment by jzabroski** [comment]
Possibly relevant is noting how xsd.exe implements this :

https://stackoverflow.com/a/16971203/1040437

**Comment by strigefleur** [comment]
It looks like RequiredAttribute is implemented as of now.

At least we have it generated on minOccurs="1" even if there's string tag.

Having [Required] messes up with mentioned earlier issue (https://stackoverflow.com/a/16971203/1040437) where you end up with error on empty string data like `<SomeTag/>`.

Is it somehow intentionall?

**Comment by mganss** [comment]
@strigefleur What's the issue with the way it's currently implemented? How can it be fixed?

**Comment by strigefleur** [comment]
Having xml element like `<SomeTag/>` assumes it's `minOccurs="1"` by default, thus the generated model property appears with `[Required]` attribute. In the same time empty tag produces by default `string.Empty` value on c# side which immediately conflicts with `[Required]` leading to failed validation.

I don't really know if there's correct way of "fixing" it since I'm [not the first](https://stackoverflow.com/a/16971203/1040437) to bump into it.

We ended up having a regex to just remove every `[Required]` on generated model string properties.

**Comment by mganss** [comment]
There's the [`AllowEmptyStrings`](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute.allowemptystrings) property. Wouldn't that solve it?

**Comment by jzabroski** [comment]
I did not know that property existed. Ha.

**Comment by mganss** [comment]
Fixed in 2.1.1142.
