### ISSUE TITLE
How to re-map simpletype to decimal instead of string?

### ISSUE THREAD

**Issue by pmeems** [mganss/XmlSchemaClassGenerator#207]
I have this type in my XSD:
```
	<xs:simpleType name="Bedrag10.2">
		<xs:restriction base="xs:decimal">
			<xs:totalDigits value="10"/>
			<xs:fractionDigits value="2"/>
		</xs:restriction>
	</xs:simpleType>
```
Used as `<xs:element name="TotLnLbPh" type="Bedrag10"/>`

This property is generated as a string:
```
        [System.Xml.Serialization.XmlElementAttribute("TotLnLbPh")]
        public string TotLnLbPh { get; set; }
```

How to tell the generator it should map `Bedrag10.2` to `decimal`?

**Comment by mganss** [comment]
I can't repro. Which version and which parameters are you using?

**Comment by pmeems** [comment]
Version 2.0.424.0
My command: 
`XmlSchemaClassGenerator.Console.exe -o ..\foo\ --disableComments --pcl -0 -n =MyNs -sf Loonaangifte2020v2.0.xsd`
I can attach the xsd if needed.

**Comment by mganss** [comment]
Yes, please attach the xsd.

**Comment by pmeems** [comment]
[Loonaangifte2020v2.0.xsd.zip](https://github.com/mganss/XmlSchemaClassGenerator/files/4651243/Loonaangifte2020v2.0.xsd.zip)

**Comment by mganss** [comment]
The element `TotLnLbPh` has type `Bedrag10`, not `Bedrag10.2` so it's not a problem with decimal. Elements that do have the type `Bedrag10.2` such as `LnLbPh` are correctly mapped to decimal. `Bedrag10` is an integer. Currently, you'll have to specify an integer datatype to use for the default case, e.g. `-ii`. If you specify `--fb` additionally, XmlSchemaClassGenerator will try to figure out the most appropriate C# type from the restrictions, in this case `long` because `Bedrag10` has a total digits restriction of 10.

**Comment by pmeems** [comment]
Thanks again for your quick reply. Adding `--fb` did the trick.
