### ISSUE TITLE
Simple types aren't generated

### ISSUE THREAD

**Issue by sharadhr** [mganss/XmlSchemaClassGenerator#271]
First off, great tool! This is *far* better than other tools for most languages—JAXB, xsd2code, [cxsd](https://github.com/charto/cxsd/) for TypeScript, etc etc. 

That said, I attempted to run xscgen on [this schema](https://www.fixm.aero/releases/FIXM-4.1.0/schemas/core/base/Types.xsd), and none of the `simpleType`s are emitted, like `AftnAddressType`, `AircraftIdentificationType`, etc. 

Can this be fixed? `Xsd.exe` also appears to have this limitation.

**Comment by mganss** [comment]
Simple types other than enums are represented by the corresponding C# type. So in your example schema, `SsrModeType` should be generated as an enum for example.

Other restrictions on simple types like `minLength` or `pattern` result in `DataAnnotation` attributes being generated. In the case of numerical types, the restrictions are used to guess the most compact numerical type that encompasses the whole range of possible values (e.g. `int` vs. `long`).

This behavior was chosen deliberately for usability reasons. It's easier to just assign a string or int value instead of having to create a wrapper class instance (possibly even multiple levels).

Did you have a different solution in mind?

**Comment by sharadhr** [comment]
> In the case of numerical types, the restrictions are used to guess the most compact numerical type that encompasses the whole range of possible values (e.g. int vs. long)

I realised this after studying the generated source code for a while longer, and came to the same conclusion that yes, this makes for simpler code, while removing unnecessary wrapper classes. One particular schema in the package, [Types.xsd](https://www.fixm.aero/releases/FIXM-4.1.0/schemas/core/base/Types.xsd) defines some very redundant types that can directly be represented in the language's native representation. 

Thanks for the response; issue closed!
