### ISSUE TITLE
Complicated output with sequence of strings compared to xsd.exe

### ISSUE THREAD

**Issue by isurakka** [mganss/XmlSchemaClassGenerator#32]
I'm trying to generate code for some .xsd files and I ran into situation where the output is not as simple as I would like. [Here are my inputs and outputs](https://gist.github.com/isurakka/124556d420f087254fc2047c4f6f836b)

Would be nice if the same simplification could be done here.

**Edit:** I just realized the simplification is actually done here but it generates one extra class which is not actually used. (foobar)

**Comment by Misiu** [comment]
@isurakka why that class is even generated? it isn't in XSD.

**Comment by mganss** [comment]
@Misiu It's the anonymous inner complex type.

**Comment by Misiu** [comment]
@mganss thanks for reply.
I've looked at generated code and I can't see usage of that complex type.
Is there a way to avoid generating it? Maybe it could be skipped if that type isn't used?

I have large XSD (splitted to 3 files), I successfully generated classes using xsd.exe but code is terrible, so I'm looking for alternatives.
I found Your repo and I'm reading issues.
I'll try Your library and hopefully output will be nicer.

**Comment by mganss** [comment]
@Misiu  In this specific case it's not used because the bar and baz elements are "shrunk" into the bar member via XmlArrayItemAttribute. If the inner complex type contained more elements the class would be needed. There is currently no way to avoid generation of this class. If you could look into this and provide a PR that'd be great.

**Comment by mganss** [comment]
Fixed by #107
