### ISSUE TITLE
bug: When using --datetime-offset deserialization of xml fails because of the DataType="dateTime" element in serialization attribute

### ISSUE THREAD

**Issue by fgheysels** [mganss/XmlSchemaClassGenerator#465]
When deserializing an Xml into a C# class that was generated by xscgen with the `--datetime-offset` flag specified, deserialization fails with this error:

> System.InvalidOperationException : 'dateTime' is an invalid value for the XmlElementAttribute.DataType property. dateTime cannot be converted to System.DateTimeOffset.

This is happening because the `DataType="datatime"` is specified on the `XmlElementAttribute`.

Fix would be to not apply the `DataType` element on DateTimeOffset properties.

**Comment by JorrenSchepers** [comment]
Hi, this fix seems to cause the `DataType` to disappear on `DateTime` types that are not replaced with `DateTimeOffset` because their `DataType` is actually `date`. This then causes those XML values to have a time component while before they did not. 
Is there any way this can be checked as well? So the remaining `DateTime`s are just dates.

**Comment by mganss** [comment]
@JorrenSchepers Fixed in 2.1.1130.
